add version from copilot that adds input validation and always pull latest docker images

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,192 +1,124 @@
-name: "Build docker image"
-description: "Build a docker image"
+name: Trivy
+description: "Run a Trivy Scan and upload the results"
+
 inputs:
-  runner_platorm:
-    type: string
-    description: "Platform of the github runner for build testing"
-    required: false
-    default: linux/amd64
-  platforms:
-    type: string
-    description: "Image platform(s)"
+  scan-type:
+    description: "type of scan: image or fs"
     required: true
-    default: linux/amd64
-  context:
     type: string
-    description: "Dockerfile Build context path"
-    required: true
-  dockerfile:
+  image-ref:
+    description: "image to scan (required if scan-type is image)"
     type: string
-    description: "Dockerfile path"
-    required: true
-  push:
+  scan-ref:
+    description: "path to scan (required if scan-type is fs)"
     type: string
-    description: "Push the image to the remote repository. Requires to be pre-authenticated to the registry. Either push or load must be true"
-    required: true
-    default: 'true'
-  build-args:
+  timeout:
+    default: 15m
     type: string
-    description: "List of build-time variables"
-    required: false
-  registry:
+  vuln-type:
+    default: "os,library"
     type: string
-    description: "Registry to push the image to"
-    required: true
-  tags:
+  severity:
+    default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
     type: string
-    description: "CSV list of tags to apply to the image"
-    required: true
-    default: latest
+  output-file:
+    default: "trivy"
   summary:
-    type: boolean
-    description: "enable github summary"
     default: true
+    type: boolean
   pr-comment:
-    type: boolean
-    description: "enable pr-comment"
     default: true
-  trivy-enabled:
     type: boolean
-    default: true
-  trivy-skip-dirs:
-    descriptipn: "skip directories to scan with trivy"
+  skip-dirs:
     type: string
-  skip-setup-trivy:
-    type: boolean
-    descriptipn: "skip trivy setup"
+  skip-setup:
     default: false
+    type: boolean
 
 runs:
   using: "composite"
   steps:
-    - name: Set up QEMU
-      uses: docker/setup-qemu-action@v3
-
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
-
-    - name: Conditionally format tags with full image + repo definition
-      id: process_tags
-      env:
-        REGISTRY: ${{ inputs.registry }}
-        TAGS: ${{ inputs.tags }}
+    - name: Validate Required Inputs
       shell: bash
       run: |
-        function process_tags() {
-            local processed_tags=()
-
-            # split tag field on comma character and add project + ${{ env.REGISTRY }} + image_name 
-            IFS=',' read -ra tags <<< "${{ env.TAGS }}"
-            for tag in "${tags[@]}"; do
-                case "$tag" in 
-                *:*)
-                    # tag includes ':' - assume preprocessed and just pass to output
-                    processed_tags+=("$tag")
-                    ;;
-                *)
-                    # tag needs to include full host + repo definition
-                    processed_tags+=("${{env.REGISTRY }}:$tag")
-                    ;;
-                esac
-            done
-
-            # format full tags into csv for docker/build-push-action
-            output_str=$(printf "%s," "${processed_tags[@]}")
-
-            # export first processed tag in list for trivy scan
-            echo "first_tag=${processed_tags[0]}" >> $GITHUB_OUTPUT
-            echo "processed=$output_str" >> $GITHUB_OUTPUT
-
-            echo "::debug::processed_tags=${processed_tags[@]}"
-            echo "::debug::output_str=$output_str"
-            echo "::debug::first_tag=${processed_tags[0]}"
-        }
-        process_tags
-
-    - name: Build container image
-      uses: docker/build-push-action@v6
-      env:
-        DOCKER_BUILD_SUMMARY: false 
-      id: docker-build
-      with:
-        platforms: ${{ inputs.runner_platform }}
-        file: ${{ inputs.dockerfile }}
-        context: ${{ inputs.context }}
-        cache-from: type=registry,ref=${{ inputs.registry }}:buildcache
-        cache-to: type=local,dest=cache
-        tags: ${{ steps.process_tags.outputs.processed }}
-        load: true
-        build-args: ${{ inputs.build-args }}
-         
-    - name: Scan for OIDC credentials
-      shell: bash
-      run: |
-        echo "Scanning for oidc credentials"
-        set +e
-        docker create --name="tmp_container" ${{ steps.docker-build.outputs.imageid }}
-        found=$(docker export tmp_container | tar tf - | grep -e "gha-creds-.*.json" | wc -l)
-        if [ $found -ge 1 ]; then
-            echo -e "::error::Found oidc credentials\nAdd the following line to your .dockerignore file\ngha-creds-*.json"
+        if [[ "${{ inputs.scan-type }}" == "image" && -z "${{ inputs.image-ref }}" ]]; then
+          echo "::error::scan-type=image requires image-ref"
+          exit 1
+        elif [[ "${{ inputs.scan-type }}" == "fs" && -z "${{ inputs.scan-ref }}" ]]; then
+          echo "::error::scan-type=fs requires scan-ref"
+          exit 1
+        elif [[ "${{ inputs.scan-type }}" != "image" && "${{ inputs.scan-type }}" != "fs" ]]; then
+          echo "::error::scan-type must be either 'image' or 'fs'"
+          exit 1
         fi
-        exit "$found"
 
-    - name: Build and push
-      env:
-        DOCKER_BUILD_SUMMARY: ${{ inputs.summary }}
-      if: ${{ inputs.push }} == true
-      uses: docker/build-push-action@v6
-      id: docker-build-push
+    - name: Run Trivy Scan
+      id: trivy
+      uses: aquasecurity/trivy-action@v0.11.1
       with:
-        platforms: ${{ inputs.platforms }}
-        file: ${{ inputs.dockerfile }}
-        context: ${{ inputs.context }}
-        push: ${{ fromJSON(inputs.push) }}
-        tags: ${{ steps.process_tags.outputs.processed }}
-        build-args: ${{ inputs.build-args }}
-        cache-from: type=local,src=cache
-        cache-to: type=registry,ref=${{ inputs.registry }}:buildcache,mode=max
-        provenance: ${{ fromJSON(false) }}
+        scan-type: ${{ inputs.scan-type }}
+        image-ref: ${{ inputs.image-ref }}
+        scan-ref: ${{ inputs.scan-ref }}
+        timeout: ${{ inputs.timeout }}
+        vuln-type: ${{ inputs.vuln-type }}
+        severity: ${{ inputs.severity }}
+        format: json
+        output: ${{ inputs.output-file }}.json
+        skip-dirs: ${{ inputs.skip-dirs }}
+        skip-setup-trivy: ${{ inputs.skip-setup }}
 
-    - name: Generate artifact attestation
-      uses: actions/attest-build-provenance@v2
-      with:
-        subject-name: ${{ inputs.registry }}
-        subject-digest: ${{ steps.docker-build-push.outputs.digest }}
-        push-to-registry: true
-
-    - name: Extract image name from registry for SBOM artifact name
-      id: sbom-artifact-name
+    - name: Derive Report Name
+      id: report-name
       env:
-        IMAGE: ${{ steps.process_tags.outputs.first_tag }}
+        IMAGE: ${{ inputs.image-ref }}
+        SCAN_REF: ${{ inputs.scan-ref }}
       shell: bash
       run: |
-        basename="${IMAGE##*/}"
-        stripped_name="${basename%:*}-${basename##*:}"
+        if [ -n "$IMAGE" ]; then
+          basename="$(basename $IMAGE)"
+          stripped_name="${basename%:*}-${basename##*:}"
+        else 
+          if [ "$SCAN_REF" == "." ]; then
+            SCAN_REF=$(pwd)
+          fi
+          basename="$(basename $SCAN_REF)"
+          random_id=$(openssl rand -hex 6)
+          stripped_name="${basename}-${random_id}"
+        fi
         echo "name=$stripped_name" >> $GITHUB_OUTPUT
 
-    - uses: anchore/sbom-action@v0
-      id: build-sbom
+    - name: Upload JSON Report
+      uses: actions/upload-artifact@v4
       with:
-        image: ${{ inputs.registry }}@${{ steps.docker-build-push.outputs.digest }}
-        output-file: ./sbom.spdx.json
-        artifact-name: sbom-${{ steps.sbom-artifact-name.outputs.name }}.spdx.json
-        dependency-snapshot: true
-     
-    - name: Generate SBOM attestation
-      uses: actions/attest-sbom@v1
+        name: ${{ steps.report-name.outputs.name }}-${{ inputs.scan-type }}-trivy
+        path: ${{ inputs.output-file }}.json
+
+    - name: Check if GHAS is Enabled
+      uses: actions/github-script@v7
+      id: ghas-check
       with:
-        subject-name: ${{ inputs.registry }}
-        subject-digest: ${{ steps.docker-build-push.outputs.digest }}
-        sbom-path: sbom.spdx.json
-        push-to-registry: true 
-    
-    - name: Run Trivy vulnerability scanner
-      uses: celo-org/trivy-composite-action@chatgpt-v3.0.0
-      if: inputs.trivy-enabled == true
+        script: |
+          const [owner, repo] = '${{ github.repository }}'.split("/");
+          const res = await github.rest.repos.get({ owner, repo });
+          const isPrivate = res.data.private;
+          const hasGhas = res.data.security_and_analysis?.advanced_security?.status === 'enabled';
+          if (isPrivate && !hasGhas) {
+            core.warning('GHAS is NOT enabled and repo is private. Cannot upload SARIF.');
+            return false;
+          }
+          return true;
+
+    - name: Convert to SARIF
+      if: fromJSON(steps.ghas-check.outputs.result)
+      id: convert-sarif
+      shell: bash
+      run: |
+        trivy convert --format sarif --output ${{ inputs.output-file }}.sarif ${{ inputs.output-file }}.json
+        echo "sarif=${{ inputs.output-file }}.sarif" >> $GITHUB_OUTPUT
+
+    - name: Upload SARIF to Security Tab
+      if: fromJSON(steps.ghas-check.outputs.result)
+      uses: github/codeql-action/upload-sarif@v3
       with:
-        image-ref: ${{ steps.process_tags.outputs.first_tag }}
-        scan-type: image
-        pr-comment: ${{ inputs.pr-comment }}
-        summary: ${{ inputs.summary }}
-        skip-dirs: ${{ inputs.trivy-skip-dirs }}
-        skip-setup: ${{ inputs.skip-setup-trivy }}
+        sarif_file: ${{ steps.convert-sarif.outputs.sarif }}
+        category: ${{ inputs.scan-type }}-${{ inputs.scan-ref != '' && inputs.scan-ref || inputs.image-ref }}
